# Generated by Django 4.0.5 on 2022-06-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=255)),
                ('nominal', models.PositiveIntegerField(default=1, help_text='Номинал')),
                ('code', models.CharField(max_length=8)),
            ],
        ),
    ]
