# Generated by Django 4.0.5 on 2022-06-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0002_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
